version: "3.7"
services:
  treamingserv:
    image: rlive
    build:
      context: .
    network_mode: host       # important for WebRTC, HomeKit, UDP cameras
    privileged: true         # only for FFmpeg hardware transcoding
    restart: unless-stopped  # autorestart on fail or config change from WebUI
    environment:
      - TZ=Asia/Ho_Chi_Minh  # timezone in logs
    volumes:
      - "./conf/groups:/apps/groups"   # folder for go2rtc.yaml file (edit from WebUI)
      - "./static:/apps/static"